name: Guestbook 📖
on:
  issue_comment:
    types: [created, edited, deleted]

permissions:
  contents: write
  issues: write

jobs:
  update_guestbook:
    name: Update Guestbook 📖
    if: ${{ github.event.issue.title == 'Guestbook' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Configure Node
        uses: actions/setup-node@v4.4.0
        with:
          node-version-file: ".node-version"

      - name: Install Dependencies
        run: npm install

      - name: Update Guestbook 📖
        run: npm run sign
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and Push Changes 📣
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am 'chore: update guestbook'
          git push
